name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GCP
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Configure docker for gcr
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 --push -t gcr.io/bubbly-monument-425111-u0/cloud-client:latest .

      - name: Verify docker image in registry
        run: |
          echo "Verifying the image in the registry"
          gcloud container images list-tags gcr.io/bubbly-monument-425111-u0/cloud-client
